name: Terraform CI/CD

# When to run the workflow
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  infracost:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -out=tfplan.binary

      - name: Convert Terraform plan to JSON
        run: terraform show -json tfplan.binary > plan.json

      # Run Terraform security scan with tfsec
      - name: Run tfsec (Terraform Security Scanner)
        uses: aquasecurity/tfsec-action@v1.0.3

      # Setup infracost
      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          version: latest

      # Run infracost breakdown
      - name: Run Infracost breakdown
        run: infracost breakdown --path plan.json --format json --out-file infracost.json

      # Post infracost comment
      - name: Post Infracost comment
        uses: infracost/actions/comment@v1
        with:
          path: infracost.json
          github-token: ${{ github.token }}
=======
name: Terraform CI/CD

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
      - run: tflint

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Save plan to JSON
        run: terraform show -json tfplan > plan.json

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          version: latest

      - name: Run Infracost breakdown
        run: infracost breakdown --path plan.json --format json --out-file infracost.json

      - name: Post Infracost comment
        uses: infracost/actions/comment@v2
        with:
          path: infracost.json
          github-token: ${{ github.token }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
>>>>>>> b780f4d (try)
